RetailBankSystemClient/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RetailBankSystemClient.Providers;
using RetailBankSystemClient.ViewModels;

namespace RetailBankSystemClient.Controllers
{
	public class CustomerController : Controller
	{
		private log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(CustomerController));

		private readonly ICustomerProvider _provider;
		public CustomerController(ICustomerProvider provider)
		{
			_provider = provider;

		}
		// GET: CustomerController
		public ActionResult Index()
		{
			if (HttpContext.Session.GetString("UserRole") != "Employee")
			{
				return RedirectToAction("Login", "Login");
			}
			return View();
		}


		[HttpGet]
		public ActionResult createCustomer()
		{
			if (HttpContext.Session.GetString("UserRole") != "Employee")
			{
				return RedirectToAction("Login", "Login");
			}
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]

		public async Task<ActionResult> createCustomer(CreateCustomer model)
		{
			if (!ModelState.IsValid)
				return View(model);

		   

			CustomerCreationStatus createSuccess = new CustomerCreationStatus();
			try
			{
				var currentdate = DateTime.Now;
				var date = DateTime.Now;
				var k = currentdate.Year - model.DateOfBirth.Year;
				if (k<=18)
				{
					ViewBag.datevalidation = "Age should be greater than 18";
					return View(model);

				}

				var response = await _provider.Createcus(model);
				if (response.StatusCode == System.Net.HttpStatusCode.OK)
				{
					var jsoncontent = await response.Content.ReadAsStringAsync();
					createSuccess = JsonConvert.DeserializeObject<CustomerCreationStatus>(jsoncontent);
					//return RedirectToAction("GetCustomer","Customer");
					return View("CreateSuccess", createSuccess);
				}
				else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
				{
					ModelState.AddModelError("", "Having server issue while adding record");
					return View(model);
				}
				else if (response.StatusCode == System.Net.HttpStatusCode.Conflict)
				{
					ModelState.AddModelError("", "Username already present with ID :" + model.CustomerId);
					return View(model);
				}
				else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
				{
					ModelState.AddModelError("", "Invalid model states");
					return View(model);
				}
			}
			catch (Exception ex)
			{
				_logger.Error("Exception occured due to  " + ex.Message);
			}
			return View(model);


		}
		[HttpGet]
		public ActionResult CreateSuccess()
		{
			CustomerCreationStatus model = new CustomerCreationStatus();
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> GetCustomerDetails(int id)
		{
			if (HttpContext.Session.GetString("UserRole") != "Employee")
			{
				return RedirectToAction("Login", "Login");
			}
			else
			{
			CustomerViewModel customer = new CustomerViewModel();
				try
				{
					var response = await _provider.GetCustomerDetails(id);
					if (response.StatusCode == System.Net.HttpStatusCode.OK)
					{
						var JsonContent = await response.Content.ReadAsStringAsync();
						customer = JsonConvert.DeserializeObject<CustomerViewModel>(JsonContent);
						return View(customer);
					}
					else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
					{
						ViewBag.Message = "No any record Found! Bad Request";
						return View(customer);
					}
					else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
					{
						ViewBag.Message = "Having server issue while adding record";
						return View(customer);
					}
					else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
					{
						ViewBag.Message = "No record found in DB for ID :" + id;
						return View(customer);
					}
				}
				catch (Exception ex)
				{
					_logger.Error("Exception occured as :" + ex.Message);
				}
				return View(customer);
			}
		}
		/// <summary>
		/// get All customers from the Customer API
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public async Task<IActionResult> GetCustomer()
		{
			if (HttpContext.Session.GetString("UserRole") != "Employee")
			{
				return RedirectToAction("Login", "Login");
			}
			else
			{
				List<CustomerViewModel> customers = new List<CustomerViewModel>();
				try
				{
					var response = await _provider.GetCustomers();
					if (response.StatusCode == System.Net.HttpStatusCode.OK)
					{
						var JsonContent = await response.Content.ReadAsStringAsync();
						customers = JsonConvert.DeserializeObject<List<CustomerViewModel>>(JsonContent);
						return View(customers);
					}
					else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
					{
						ViewBag.Message = "Having server issue while adding record";
						return View(customers);
					}

				}
				catch (Exception ex)
				{
					_logger.Error("Exceptions occured due to :" + ex.Message);
				}
				return View(customers);
			}
		}
	}
}

RetailBankSystemClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RetailBankSystemClient.Models;

namespace RetailBankSystemClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RetailBankSystemClient/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RetailBankSystemClient.Providers;
using RetailBankSystemClient.ViewModels;

namespace RetailBankSystemClient.Controllers
{
    public class TransactionController : Controller
    {
        private log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(TransactionController));
        // GET: TransactionController
        private ITransactionProvider _transactionProvider;
        public TransactionController(ITransactionProvider transactionProvider)
        {
            _transactionProvider = transactionProvider;

        }
        [HttpGet]
        public async Task<ActionResult> TransactionHistory(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == null)
            {
                return RedirectToAction("Login", "Login");
            }
            //else
            //{
            List<TransactionHistoryViewModel> model = new List<TransactionHistoryViewModel>();
                try
                {
                    var response = await _transactionProvider.GetTransactions(id);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var JsonContent = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<List<TransactionHistoryViewModel>>(JsonContent);
                        return View(model);
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        ViewBag.Message = "Having server issue while adding record";
                        return View(model);
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        ViewBag.Message = "Internal Server Error! Please try again later";
                        return View(model);
                    }
                }
                catch (Exception ex)
                {
                   _logger.Error("Exceptions occured due to " + ex.Message);
                }
                return View(model);
            //}
           
        }

      
    }
}

RetailBankSystemClient/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>*@

@{

    int? userid = Context.Session.GetInt32("UserId");


    string username = Context.Session.GetString("Username");


}


    <div class="container-fluid">

        <div id="carouselExampleFade" class="carousel slide carousel-fade ml-0" data-ride="carousel">
            <div class="carousel-inner">

                <div class="carousel-item active">
                    <img class="d-block w-100" src="~/Images/Banking.jpg" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="text-white font-weight-bold">Welcome to E-Banking </h2>

                    </div>
                </div>
                <div class="carousel-item ">
                    <img class="d-block w-100" src="~/Images/Agreement.jpg" alt="First slide">
                    <div class="carousel-caption d-none d-md-block text-dark">
                        <h2 class="text-dark font-weight-bold">Reliable</h2>

                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/Images/credit.jpg" alt="Third slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="font-weight-bold text-dark">Convienient</h2>

                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>




    </div>
    <div class="container paral paralsec pt-5 mt-3" style="width:1080px;">
        <h1 class="display-3">Here is a heading 1</h1>
        <p class="lead">Here is a short description 1</p>

    </div>



    <div class="container-fluid  p-4">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 ">
                <div class="card" style="width: auto;object-fit:cover">
                    <div class="box1">
                        <img src="~/Images/BankAccount.png" style="object-fit: cover;" alt="">
                        <h3 class="title">
                            <ul style="list-style:none;">
                                <li>
                                    @*asp-route-id="@item.CustomerId"*@
                                    <a class=" text-white" style="text-decoration:none;" asp-area="" asp-controller="Account" asp-action="GetCustomerAccount" asp-route-id=@userid>Your Accounts</a>
                                </li>
                                @*<li>
                                        <a class=" text-dark" asp-area="" asp-controller="Account" asp-action="getAccountStatement">AccountStatements</a>
                                    </li>*@
                            </ul>
                        </h3>

                    </div>

                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card" style="width: auto;">
                    <div class="box1">
                        <img src="~/Images/Transactions.jpg" alt="">
                        <h3 class="title text-white">
                            <ul style="list-style:none;">
                                <li>
                                    <a class=" text-white" style="text-decoration:none;" asp-area="" asp-controller="Account" asp-action="Deposit">Deposit</a>
                                </li>
                                <li>
                                    <a class=" text-white" style="text-decoration:none;" asp-area="" asp-controller="Account" asp-action="AccountsForWithdrawAndTransfer" asp-route-id=@userid>Withdraw and Transfer</a>

                                </li>

                                <li>
                                    <a class=" text-white" style="text-decoration:none;" asp-area="" asp-controller="Transaction" asp-action="TransactionHistory" asp-route-id=@userid>Transaction History</a>

                                </li>
                            </ul>
                        </h3>

                    </div>

                </div>
            </div>

        </div>
    </div>

    @if (Context.Session.GetString("UserRole") == "Employee")
    {
        <div class="container p-4">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="card" style="width: auto;object-fit:cover">
                        <div class="box1">
                            <img src="~/Images/bg3.jpg" style="object-fit: cover;" alt="">
                            <h3 class="title">
                                <ul style="list-style:none;">
                                    <li>
                                        <a class="text-white" style="text-decoration:none;" asp-area="" asp-controller="Customer" asp-action="createCustomer">Create Customer</a>
                                    </li>
                                    <li>
                                        <a class=" text-white" style="text-decoration:none;" asp-area="" asp-controller="Customer" asp-action="GetCustomer">Get All Customers</a>
                                    </li>
                                </ul>
                            </h3>

                        </div>

                    </div>
                </div>


            </div>
        </div>
    }